version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: n3u3da!
      MYSQL_DATABASE: portfolio_management

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql
      # Ensure the database schema is initialized on first container start
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

    networks:
      - springboot-network

  springboot-app:
    build: .
    container_name: springboot_container

    depends_on:
      - mysql

    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/portfolio_management
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: n3u3da!

    ports:
      - "8082:8080"

    networks:
      - springboot-network

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nginx-server
    ports:
      - "8085:80"
    depends_on:
      - springboot-app
    networks:
      - springboot-network

volumes:
  mysql-data:

networks:
  springboot-network:
