spring.application.name=portfoliomanager
spring.datasource.url=jdbc:mysql://localhost:3306/portfolio_management
spring.datasource.username=root
spring.datasource.password=n3u3da!

server.port=8080
gold.api.baseUrl=https://www.goldapi.io/api/XAU/INR
gold.api.key=goldapi-abad608decd86d6744e6b1879d8d27a0-io