spring.application.name=portfoliomanager
spring.datasource.url=jdbc:mysql://localhost:3306/portfolio_management
spring.datasource.username=root
spring.datasource.password=n3u3da!

server.port=8080
risk.analysis.risk-free-rate=0.04
gold.api.baseUrl=https://www.goldapi.io/api/XAU/INR
gold.api.key=goldapi-abad608decd86d6744e6b1879d8d27a0-io

pexels.api.base-url=https://api.pexels.com/v1/search
pexels.api.key=CFPliSZNrDiJj8vlY3ruj67Q8BSFNrkx7ycmXN3BzUJBwdxyLwLCsiyt
